spring.application.name=delivery-tracking

spring.datasource.url=jdbc:postgresql://localhost:5432/{{YOUR_DATABASE_NAME}}
spring.datasource.username=YOUR_USER_NAME
spring.datasource.password=YOUR_PASSWORD

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=3s
spring.data.redis.connect-timeout=3s
spring.data.redis.database=0


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=CHANGE_THIS_TO_A_LONG_SECRET_KEY_MIN_32_CHARS
jwt.access-token-expiration=3600000