CREATE TABLE restaurants(
	id BIGSERIAL PRIMARY KEY NOT NULL,
	user_id BIGSERIAL NOT NULL,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	address VARCHAR(255) NOT NULL,
	city VARCHAR(50) NOT NULL,
	postal_code VARCHAR(10) NOT NULL,
	status VARCHAR(20) NOT NULL,
	modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL,
	
	CONSTRAINT FK_restaurants_user_id
		FOREIGN KEY (user_id)
		REFERENCES users(id)
		ON UPDATE NO ACTION
		ON DELETE NO ACTION
)